# Generated by Django 5.2.1 on 2025-05-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_github_repo',
            field=models.BooleanField(default=False),
        ),
    ]
