# Generated by Django 5.2.1 on 2025-05-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_folder_content_folder_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
    ]
