# Generated by Django 5.2.1 on 2025-05-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_content'),
        ('projects', '0002_project_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('last_commit_hash', models.CharField(blank=True, max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_files', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'path'], name='files_gitfi_project_37b9b5_idx')],
                'unique_together': {('project', 'path')},
            },
        ),
    ]
