# Generated by Django 5.2.1 on 2025-05-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_gitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
