# Generated by Django 5.2.1 on 2025-05-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='content',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='folder',
            name='file_count',
            field=models.IntegerField(default=0),
        ),
    ]
