# Generated by Django 5.2.1 on 2025-05-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileevent',
            old_name='file',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='fileevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'File Created'), ('modified', 'File Modified'), ('deleted', 'File Deleted')], default='created', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileevent',
            name='file_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_events', to='projects.project'),
        ),
    ]
