# Generated by Django 5.2.1 on 2025-05-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_folder_content_folder_file_upload'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Supports Markdown, LaTeX math ($$...$$), and code blocks (```language ...```)')),
                ('rendered_html', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='files.file')),
                ('folder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='files.folder')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='NoteTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='notes.note')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='notes.notetag')),
            ],
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['file'], name='notes_note_file_id_3d5f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['folder'], name='notes_note_folder__c35bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['project'], name='notes_note_project_970138_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True), ('project__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False), ('project__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', True), ('project__isnull', False)), _connector='OR'), name='note_has_one_parent'),
        ),
        migrations.AlterUniqueTogether(
            name='notetagging',
            unique_together={('note', 'tag')},
        ),
    ]
