# Generated by Django 5.2.1 on 2025-05-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_gitfile'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='note',
            name='note_has_one_parent',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_file_id_3d5f1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_folder__c35bc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_project_970138_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='files.file'),
        ),
        migrations.AlterField(
            model_name='note',
            name='rendered_html',
            field=models.TextField(blank=True, default='', editable=False),
            preserve_default=False,
        ),
    ]
